### ISSUE TITLE
ABI break?   dnnl::impl::cpu::get_max_cpu_isa(bool)  symbol disapeared

### ISSUE THREAD

**Issue by fenrus75** [oneapi-src/oneDNN#788] opened 2020-07-22 15:20 UTC
# Summary
It seems that in the 1.5.1 release, the dnnl::impl::cpu::get_max_cpu_isa(bool) symbol dropped out of the library

# Version
1.4 had it, our 1.5.1 build does not

is this break of the ABI deliberate?

**Comment by emfomenk** [comment] 2020-07-22 15:28
Hi @fenrus75,

Could you please elaborate on what exactly is broken?

The thing is that `dnnl::impl` namespace and all functions in it are an implementation of the library that could change from release to release. So, I wouldn't expect any external libraries or applications to use those, hence the function (re)movement isn't really an ABI break. 

It is also worth mentioning that for the users we introduced [`cpu_isa dnnl::get_effective_cpu_isa()`](https://oneapi-src.github.io/oneDNN/group__dnnl__api__service.html#ga3953f71c3f0126d9cc005a1ceff65e8b) API to query the effective ISA oneDNN is using.

**Comment by fenrus75** [comment] 2020-07-22 15:30
So this symbol was exported before, and now it isn't , and that flagged our ABI checks.

Maybe this was just a case that it should not be exported in the first place, and that's great.. just wanted to report it to make sure it was a deliberate change

(also making symbols not exported when they shouldn't is a good thing... both for performance as well as ABI hygiene)

**Comment by emfomenk** [comment] 2020-07-22 15:40
Oh, I see. Thanks for the report. That was indeed a deliberate decision.

I agree with you on the usefulness of non-exporting the internal symbols.
That is what we do by default for the most of the internal functionally.

However, for the sake of testing, we sometime really-really need to use the internal symbols. Before we exposed the functions mentioned above, there was no way for our tests to identify what platform they are running on. To not re-implement the code we decided to export this particular symbol to make it accessible for our tests. That is a trade-off between code duplication (of course we could re-implement the dispatcher in the tests) and purity of the API/ABI (non-exporting the internal symbols). Once we introduce a user-level API to get the ISA, there was no need to export the internal symbol anymore (hence, this change).

There are few other places in the library that we expose for the same reason.
The current list looks like this (putting aside gemm functions):
``` bash
$ grep DNNL_API -R src/
src/common/bfloat16.hpp:37:    bfloat16_t DNNL_API &operator=(float f);
src/common/bfloat16.hpp:39:    DNNL_API operator float() const;
src/common/primitive_attr.cpp:549:status_t DNNL_API dnnl_primitive_attr_set_rnn_tparams(
src/common/type_helpers.hpp:36:extern memory_desc_t DNNL_API glob_zero_md;
src/common/utils.cpp:238:void DNNL_API activate_threadpool(threadpool_iface *tp) {
src/common/utils.cpp:243:void DNNL_API deactivate_threadpool() {
src/common/memory_debug.hpp:61:void DNNL_API *malloc(size_t size, int alignment);
src/common/primitive_cache.hpp:106:status_t DNNL_API get_primitive_cache_size(int *size);
src/cpu/platform.hpp:80:bool DNNL_API has_data_type_support(data_type_t data_type);
src/cpu/x64/cpu_isa_traits.hpp:85:cpu_isa_t DNNL_API get_max_cpu_isa_mask(bool soft = false);
```

**Comment by emfomenk** [comment] 2020-07-30 02:34
Seems like the issue is addressed, so I am closing the issue.
@fenrus75, thank you for the concern and acute attention to the details!

**Closed by emfomenk** 2020-07-30 02:34 UTC
Labels: sighting
