### ISSUE TITLE
build error with Visual Studio 2019 in Windows

### ISSUE THREAD

**Issue by ghost** [oneapi-src/oneDNN#856] opened 2020-10-23 22:50 UTC
Hi, 

I get a build error when I try to compile the latest sources  under Windows 10 with Visual Studio 2019:

jit_uni_x8s8s32x_1x1_conv_kernel.cpp 

line 688:  std::back_inserter(jcp.post_ops.entry_));

error C2039: 'back_inserter' in not a member of 'std'
error C3861: 'back_inserter' indentifier not found

when I add
`#include <iterator>`

everything compiles just fine

thanks

**Comment by igorsafo** [comment] 2020-10-23 22:54
Hi @zulma46 , thanks for your finding! Indeed looks like we don't include required header. I will take a look at it and will update you once the issue is reproduced and fixed.

**Comment by vpirogov** [comment] 2020-10-28 01:22
Fixed by a8ed7bcc2991a738650b081b1e2072916a97745e.

**Closed by vpirogov** 2020-10-28 01:22 UTC
Labels: bug
