### ISSUE TITLE
Why are the convolutional inference results of OneDNN very different from the convolutional structure of pytorch?

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1810] opened 2024-02-23 09:22 UTC
1. Machine environment: windows system, vs2022; cpu is Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90; and the version of oneDNN is 3.3.4;
2. the model weights is convert with onnx, with pytorch's checkpiont; the input image is same the pytorch's inference.
3. oneDNN convolution code:

typedef struct tagNetOneDNN
{
    stream                                          netStream;   /* stream */
    std::vector<primitive>                          net;         /* primitive */
    std::vector<std::unordered_map<int, memory>>    netArgs;     /* argument */
}net_oneDNN;

typedef struct tagSegModel
{
    net_weight netWeight; // weight
    net_oneDNN netOneDnn; // net of oneDNN

    engine::kind netEngKind;
    engine netEng;
    memory conv_weights;
    memory conv_bias;
    memory input_data_mem;
    memory input_mask_mem;
    memory conv_src;
    memory conv_dst;

    std::vector<float> fMeans;
    std::vector<float> fStd;
    std::vector<int32_t> inputShape;
    std::vector<int32_t> maskShape;
    int32_t iModelW;
    int32_t iModelH;
    float   fNormCoef;
    float *inputData;
    float *maskData;
    imgInfo maskImg;

}seg_model;

int32_t initModel(seg_model &segNet)
{
    std::vector<int32_t> concatIn0 = {1, 3, 224, 384};
    std::vector<int32_t> concatIn1 = {1, 1, 224, 384};
    std::vector<int32_t> convIn    = {1, 4, 224, 384};
    std::rector<int32_t> convOut   = {1,32,112,192};
    int32_t convStrid = 2;
    int32_t convPad   = 1;
    int32_t isActive = 1;
    int32_t isRelu   = 1;
    std::string opName = "backbone.stage0";

    if (0 != ConcatOp(segNet, concatIn0, concatIn1))
    {
        return -1;
    }

    if (0 != ConvOp_new(segNet, opName, convIn, convOut, convStrid, isActive, isRelu))
    {
        return -1;
    }

    return 0;

}

int32_t concat_test(imgInfo &img, seg_model & segNet)
{

    if (segNet.netWeight.ops.size() <= 0)
    {
        std::cout << " the weights of net ops is null !" << std::endl;
        return -1;
    }

    int32_t isFailed = 0;
    int32_t isStart = 0;

    if (0 != ImageConvert(img, segNet.fNormCoef, segNet.fMeans, segNet.fStd, segNet.inputData))
    {
        std::cout << " failed to normalize the input image !" << std::endl;
        return -1;
    }

    write_to_dnnl_memory(segNet.inputData, segNet.input_data_mem);

    for (int32_t idx = 0; idx < 3; idx++)
    {
        segNet.netOneDnn.net.at(idx).execute(segNet.netOneDnn.netStream, segNet.netOneDnn.netArgs.at(idx));

    }

    return 0;
}

3. result and the weight of convolution
see attached
[pytorch_conv_result.txt](https://github.com/oneapi-src/oneDNN/files/14383527/pytorch_conv_result.txt)

[pytorch_concat_result.txt](https://github.com/oneapi-src/oneDNN/files/14383550/pytorch_concat_result.txt)

[oneDNN_concat_result.txt](https://github.com/oneapi-src/oneDNN/files/14383558/oneDNN_concat_result.txt)
[oneDNN_conv_result.txt](https://github.com/oneapi-src/oneDNN/files/14383559/oneDNN_conv_result.txt)

4. Questions
 why is large different result bottom, please help me,thanks.

**Comment by feixuedudiao** [comment] 2024-02-23 09:24
Do I need to use the pytoch version of oneDNN to convert model parameters from pytorch checkpoint to onnx?

**Comment by vpirogov** [comment] 2024-02-23 17:26
Converting model parameters from Pytorch checkpoint to ONNX has nothing to do with oneDNN. I would guess that the difference in result you see is caused by using incorrect memory format for the weights or activations or both. [Getting started](https://oneapi-src.github.io/oneDNN/page_getting_started_cpp.html#wrapping-data-into-a-onednn-memory-object) section of the Developer Guide may help.

**Comment by feixuedudiao** [comment] 2024-02-26 01:10
thks . i think it may be right for the mmeory of weights, above is the convolution code:
 int32_t ConvOp_new(seg_model &segNet,std::string opName, std::vector<int32_t> inShape,
                    std::vector<int32_t> outShape, int32_t stride, int32_t isActive, int32_t isRelu)
{
    const float negative_slope = 0.0f;
    int32_t ioSize             = 1;
    int32_t convPadding        = 0;
    int32_t isDw               = 0;
    std::string opWeightName    = opName + ".weight";
    std::string opBiasName      = opName + ".bias";
    net_op opWeight;
    net_op opBias;

    if (segNet.netWeight.ops.size() <= 0 || segNet.netWeight.ops.size() <= 0)
    {
        std::cout << "the weight of net is empyty!!" << std::endl;
        return -1;
    }

    auto netWeight              = segNet.netWeight;
    auto netOneDnn              = segNet.netOneDnn;
    if(netWeight.ops.count(opWeightName) <= 0 || netWeight.ops.count(opBiasName) <= 0)
    {
        return -1;
    }

    net_op conv_weight_op       = netWeight.ops[opWeightName];
    net_op conv_bias_op         = netWeight.ops[opBiasName];
    auto   weightShape          = conv_weight_op.shapes;
    float *userWeights          = &conv_weight_op.weights[0];
    const float *userBias       = &conv_bias_op.weights[0];
    memory::dims conv_inp_tz    = intVecToDims(inShape);
    memory::dims conv_out_tz    = intVecToDims(outShape);
    memory::dims conv_bias_tz   = intVecToDims(conv_bias_op.shapes);

    /* the kernel is 3x3, to padding */
    if ((weightShape[2] == 3) && (weightShape[3] == 3))
    {
        convPadding = 1;
    }

    if (weightShape[1] == 1)
    {
        isDw        = 1;
    }

    std::vector<int32_t> tmp_weight_tz = {conv_weight_op.shapes[0], ioSize, ioSize, conv_weight_op.shapes[2],
                                conv_weight_op.shapes[3]};
    memory::dims conv_weights_tz= isDw ? intVecToDims(tmp_weight_tz) : intVecToDims(conv_weight_op.shapes);
    memory::dims conv_strides   = {stride, stride};
    memory::dims conv_paddings  = {convPadding, convPadding};

    /* create memory descriptors for convolution */
    auto user_weights_md        = memory::desc({conv_weights_tz},   dt::f32, tag::any);
    auto conv_bias_md           = memory::desc({conv_bias_tz},      dt::f32, tag::any);
    auto conv_weight_md         = memory::desc({conv_weights_tz},   dt::f32, tag::any);
    auto conv_src_md            = memory::desc({conv_inp_tz},       dt::f32, tag::any);
    auto conv_dst_md            = memory::desc({conv_out_tz},       dt::f32, tag::any);

    // create memory for weight from model parmameter, oihw layout is assumed for weight, and x or a for bias
    auto user_weight_mem           = memory({{conv_weights_tz},   dt::f32, isDw ? tag::goihw : tag::oihw},
                                    segNet.netEng, (float*)userWeights);
    segNet.conv_bias               = memory({{conv_bias_tz}, dt::f32, tag::x}, segNet.netEng);
    {
        auto ptr = segNet.conv_bias.map_data();
        ::memcpy(ptr, userBias, conv_bias_op.weights.size());
        segNet.conv_bias.unmap_data(ptr);
    }

    /* the active, if the isRelu is true , it is relu, or not is hardswish */
    post_ops conv_ops;
    primitive_attr conv_attr;
    if (isActive)
    {
        int32_t testVal = isRelu ? 1 : 0;
        conv_ops.append_eltwise(isRelu ? algorithm::eltwise_relu : algorithm::eltwise_hardswish, negative_slope, negative_slope);
    }
    conv_attr.set_post_ops(conv_ops);

    /* create a convolution */
    auto conv_pd                = convolution_forward::primitive_desc(segNet.netEng,
                                    prop_kind::forward_inference, algorithm::convolution_direct,
                                    conv_src_md, conv_weight_md, conv_bias_md, conv_dst_md,
                                    conv_strides, conv_paddings, conv_paddings, conv_attr);
    auto conv_src_mem   = segNet.conv_src;
    if(conv_pd.src_desc() != segNet.conv_src.get_desc())
    {
        conv_src_mem = memory(conv_pd.src_desc(), segNet.netEng);
        auto rd = reorder(segNet.conv_src, conv_src_mem);
        segNet.netOneDnn.net.push_back(rd);
        segNet.netOneDnn.netArgs.push_back({{DNNL_ARG_FROM, segNet.conv_src},
                                           {DNNL_ARG_TO,    conv_src_mem}});
    }

    /* the memory of weights */
    segNet.conv_weights = user_weight_mem;
    if (conv_pd.weights_desc() != user_weight_mem.get_desc())
    {
        segNet.conv_weights = memory(conv_pd.weights_desc(), segNet.netEng);
        auto rd = reorder(user_weight_mem, segNet.conv_weights);
        rd.execute(segNet.netOneDnn.netStream, user_weight_mem, segNet.conv_weights);
    }

    /* the memory of dst */

    segNet.conv_dst = memory(conv_pd.dst_desc(), segNet.netEng);

    /* create convolution primitive and add it to net */
    segNet.netOneDnn.net.push_back(convolution_forward(conv_pd));
    segNet.netOneDnn.netArgs.push_back({{DNNL_ARG_SRC,      conv_src_mem},
                                        {DNNL_ARG_WEIGHTS,  segNet.conv_weights},
                                        {DNNL_ARG_BIAS,     segNet.conv_bias},
                                        {DNNL_ARG_DST,      segNet.conv_dst}});

    /* update the memory of conv src */
    segNet.conv_src             = segNet.conv_dst;

    return 0;
}

**Comment by shu1chen** [comment] 2024-02-26 03:11
@feixuedudiao I took a quick look at the code snippet you provided, it seems that `rd.execute(...)` is missing in the code block `if(conv_pd.src_desc() != segNet.conv_src.get_desc()) {...}`. Could you please refer to the example [convolution.cpp](https://github.com/oneapi-src/oneDNN/blob/main/examples/primitives/convolution.cpp) for this primitive and see if anything else is missing or incompletely configured?

**Comment by shu1chen** [comment] 2024-03-04 02:30
@feixuedudiao Has your question been resolved by trying the ways I suggested? Any update?

**Comment by shu1chen** [comment] 2024-03-14 01:46
@feixuedudiao Has your question been resolved? I will close this issue in 7 days if there is no more update.

**Closed** 2024-03-20 03:12 UTC
Labels: question
