### ISSUE TITLE
How to correctly calculate in8 matrix multiplication on a machine that does not support AVX512_VNNI instruction set use dnnl_gemm_s8s8s32 ?

### ISSUE THREAD

**Issue by JeneyWang** [oneapi-src/oneDNN#717] opened 2020-04-27 02:53 UTC
I want to use mkldnn dnnl_gemm_s8s8s32 api to calculate matrix multiplication [-128 ~ 127] of int8, but my machine does not support avx512_vnni instruction set, I tested some scales, and the results are different from manual calculation (for loop). 
Here are my machine models:  
Intel(R) Xeon(R) Glod 6140 CPU @ 2.30GHz, the highest instruction set supported may be avx512.
In addition, I have separately tested that I first subtracted 128 from A, converted it into uint8, called cblas of MKL(cblas_gemm_u8s8s32), and then added B * 128 to the output result, which is consistent with the direct call to dnnl_gemm_s8s8s32, unfortunately, they are not consistent with the actual results.
I wonder if I can turn off the call vnni instruction set when compiling mkldnn / onednn? Or is there any other method to calculate the int8 matrix multiplication call dnnl_gemm_s8s8s32  correctly。

**Comment by rsdubtso** [comment] 2020-04-27 06:07
Hi @JeneyWang. The problem seems to be not due to the fact that oneDNN uses vnni instructions, but due to the fact that when vnni instructions are not available oneDNN uses an instruction sequence where one of the intermediate accumulators is 16-bit wide and may overflow. The problem is described in more details in the documentation page [Int8 Computation Aspects](https://oneapi-src.github.io/oneDNN/dev_guide_int8_computations.html).

**Comment by JeneyWang** [comment] 2020-04-27 06:29
Hi @rsdubtso 
Thank you for your reply.

I had seen the introduction of dnnl int8. That is to say, on machines that do not support vnni instruction set, will there be overflow risk when I use dnnl_gemm_s8s8s32 of oneDNN to calculate int8 matrix multiplication [int8 actual range]? 

What I want to ask is, is there any optional way for the bottom layer of oneDNN / MKL to calculate int8 multiplication without vnni instruction, or is there any int8 matrix multiplication implemented with avx2 / avx512 instruction set?
How can I use this interface correctly to get the correct int8 matrix multiplication result.  Or is it necessary to use dnnl_gemm_s8s8s32 or cblas_gemm_ s8u8s32 API to get accurate results on the machine supporting vnni instruction set?

**Comment by rsdubtso** [comment] 2020-04-27 16:06
> What I want to ask is, is there any optional way for the bottom layer of oneDNN / MKL to calculate int8 multiplication without vnni instruction, or is there any int8 matrix multiplication implemented with avx2 / avx512 instruction set?

Yes, there is a way to do this on pre-vnni machines: first the `s8`/`u8` inputs need to be sign/zero-extended to `s16` via `pmovsxbw`/`pmovzxbw`, then `s16` values need to be multiplied via `pmaddwd` (there would be no overflow as the values will be in the `s8`/`u8` range), and the `s32` result need to be accumulated via `paddd`. However, this is slow (fewer MACs per cycle as they are performed with 16-bit integers). oneDNN does not implement this because More often than not it is OK to scale the weights into 7 bits.

If you can make a case for requiring full range (except for unit tests :)), please let us know.

**Comment by emfomenk** [comment] 2020-04-27 16:31
Minor side comment.

If you go from s8s8 case to u8s8, you need to **add** `128` to matrix `A` (to move `[-128 .. 127]` range to `[0, 255]`), call `u8s8s32_gemm()` and then **subtract** `128 * B` from the result. From the comment it seems you did the opposite: 

> In addition, I have separately tested that I first **subtracted** 128 from A, converted it into uint8, called cblas of MKL(cblas_gemm_u8s8s32), and then **added** B * 128 to the output result, which is consistent with the direct call to dnnl_gemm_s8s8s32, unfortunately, they are not consistent with the actual results.

Maybe, that was just a typo.

**Comment by vpirogov** [comment] 2020-05-06 15:47
Closing due to lack of activity. Feel free to reopen with new data.

**Closed by vpirogov** 2020-05-06 15:47 UTC
Labels: sighting
