### ISSUE TITLE
The examples for convolution/deconvolution driver documentation are out of date

### ISSUE THREAD

**Issue by lb991** [oneapi-src/oneDNN#1253] opened 2022-01-27 20:30 UTC
# Summary
The convolution/deconvolution driver examples have wrong paths for the --batch option

# Version
master branch (at least)

# URLs
https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/doc/driver_conv.md
https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/inputs/conv/test_conv_all

# Observed behavior
Instead of the inputs/conv/test_conv_all path for the --batch option, inputs/conv/conv_all path is present which is wrong as the benchdnn shapes should be in test_conv_all.

# Expected behaviour
All the Convolution/Deconvolution examples should point to inputs/conv/test_conv_all instead of inputs/conv/conv_all.

**Comment by igorsafo** [comment] 2022-01-27 22:07
Hi @lb991 ,

Thanks for the issue, indeed the code in documentation is outdated. We will notify you once the issue is fixed.

Regards,
Igor Safonov

**Comment by lb991** [comment] 2022-01-28 09:50
Thanks @igorsafo ! Much appreciated!

**Comment by vpirogov** [comment] 2022-02-09 17:43
Fixed by 7d913c4c85eff868dd1fbbe0294a03e320c868fc

**Closed by vpirogov** 2022-02-09 17:43 UTC
Labels: documentation
