### ISSUE TITLE
Wrong output for DeConvolution

### ISSUE THREAD

**Issue by pranathibl** [oneapi-src/oneDNN#803] opened 2020-08-11 04:57 UTC
Hi,

For some specific Stride and Filter sizes output is not correct. and for every run, output is different for the same input.
This is the setup i have used  [TransposedConv_standalone.zip](https://github.com/oneapi-src/oneDNN/files/5054814/TransposedConv_standalone.zip)

version used - v1.0

Thanks,
Pranathi

**Comment by alokbakshi** [comment] 2020-08-11 12:47
Hi @pranathibl 

Could you please post the log information for `MKLDNN_VERBOSE=1 ./transposedConvLayer_exe` to assist in debugging.

I have not been able to reproduce the issue so far having gotten the same output in output.txt file while executing the attached code with mkldnn-v1.0.4 on avx2 or avx512 ISA with varying number of threads.

**Comment by pranathibl** [comment] 2020-08-12 07:25
Hi @alokbakshi 

I am seeing wrong outputs for multiple run. output is not same for each run.
I have created a setup to run it multiple times. Can you verify with this?
[TransposedConv_standalone_multiple.zip](https://github.com/oneapi-src/oneDNN/files/5061211/TransposedConv_standalone_multiple.zip)

- Pranathi

**Comment by tprimak** [comment] 2020-08-12 21:25
Hi @pranathibl Could you please check if the same behavior is observed for v1.6?

**Comment by alokbakshi** [comment] 2020-08-12 23:05
Hi @pranathibl 

I have run your attached code on Linux machine (avx, avx2 and avx512 ISA) and on windows (avx2 isa) machine but could not reproduce the behavior -- namely different output in each run -- that you observed.

I am assuming (based upon the exe extension) that you are running it on windows machine. Could you please post the output info from the following command:
`set MKLDNN_VERBOSE=1`                     
`transposedConvLayer_exe` 

... using that it would be easier to pinpoint the particular ISA the deconvolution primitive (and reorders) are being run on.

**Comment by vpirogov** [comment] 2020-09-16 23:26
Closing the issue as we are unable to reproduce it. Feel free to reopen or submit a new one with additional data.

**Closed by vpirogov** 2020-09-16 23:26 UTC
Labels: sighting
