### ISSUE TITLE
[aarch64] Update xbyak_aarch64

### ISSUE THREAD

**Issue by densamoilov** [oneapi-src/oneDNN#1518] opened 2022-12-12 21:22 UTC
We found that there is an issue with identifying cache sizes on macOS with M chip. We implemented a fix in master and rls-v3.0.  The fix is here: ba91a536cb59558b3f3880951def160fe24b2820.

I also found that the issue has been fixed in the xbyak_aarch64 repository: https://github.com/fujitsu/xbyak_aarch64/pull/71/commits/eef8e10d21632c71f6756c5a7f1ae5ecf6339e54. 

@nSircombe, can you please update xbyak_aarch64 in master?

**Comment by nSircombe** [comment] 2022-12-12 21:23
This is probably one for @kawakami-k I think.

**Comment by kawakami-k** [comment] 2022-12-13 00:19
@densamoilov @nSircombe 
Thanks for letting me know about the bug. I will send a pull request to update Xbyak_aarch64 in oneDNN by the end of this month, after confirming Xbyak_aarch64 can obtain correct cache size for Graviton3.
Thank you!

**Comment by densamoilov** [comment] 2022-12-13 00:22
Thank you guys for a quick response. Sounds good to me.

**Comment by anthony-linaro** [comment] 2023-01-31 10:47
Hi All,

Is there any movement on this?

I am working on Blender for Windows on Arm, and merging in the latyest xbyak would be of great help, as it contains support for MSVC (https://github.com/fujitsu/xbyak_aarch64/pull/72), which would help in my endeavour of enabling OIDN

**Comment by kawakami-k** [comment] 2023-02-01 00:09
I hope to submit a pull request to update Xbyak_aarch64 to the latest version this weekend.
Sorry, please wait a little longer.

**Comment by anthony-linaro** [comment] 2023-02-09 17:40
Thanks, I will keep an eye out for your PR

**Comment by kawakami-k** [comment] 2023-02-12 10:43
The fix for Xbyak_aarch64 is almost finished. I will pull it soon.
https://github.com/fujitsu/xbyak_aarch64/tree/e9138219a4526c05c7ced3931e2b1107501c4a59

**Comment by kawakami-k** [comment] 2023-02-14 13:52
This PR updates Xbyak_aarch64 to the latest version. 
https://github.com/oneapi-src/oneDNN/pull/1557
This version of Xbyak_aarch64 can run on Windows Dev Kit 2023, but I have not checked if oneDNN of this PR works well on Dev Kit 2023. I'd be glad to get feedback.

Thank you!

**Comment by kawakami-k** [comment] 2023-02-18 01:19
@anthony-linaro 
Thank you for the feedback. 
I'll try your patch.

**Comment by anthony-linaro** [comment] 2023-02-23 15:46
No problem - let me know if you have any issues I can help with

**Comment by anthony-linaro** [comment] 2023-03-09 10:45
Hi @kawakami-k - did you get chance to have a look?

**Comment by kawakami-k** [comment] 2023-03-12 05:59
@anthony-linaro 
I made a path for Windows on Arm.
https://github.com/kawakami-k/oneDNN/commits/windows_on_arm

Build is ok, but tests are failed.

**Comment by kawakami-k** [comment] 2023-03-12 06:19
@anthony-linaro 
Yes, I tried your patch on Windows DevKit 2023 (Windows11 on Qualcom's Arm CPU). 
I also modified `cpu_isa_traits.hpp`.
https://github.com/kawakami-k/oneDNN/commit/f989729ebe5315aca61bb820a48f74fbff08aa79

Build is ok, but tests are failed. For example, the first JIT-ed test pattern of `tests/gtests/test_reorder` generated JIT-ed code and used it. It may be working well up to this step, but the test was stopped wtih 0xC0000005 (memory access vaiolation?) before starting the second test pattern.  I suspect that memory allocation of Xbyak_aarch64 may have gone wrong, but I have not been able to investigate the cause.

**Comment by anthony-linaro** [comment] 2023-03-13 10:28
@kawakami-k Is this something you intend to investigate, or something you would like me to look into?

**Comment by kawakami-k** [comment] 2023-03-13 11:16
@anthony-linaro 
I would be happy if you could do it. I may not have time this month...

**Comment by vpirogov** [comment] 2023-03-23 20:58
The original issue is addressed by #1557.

@anthony-linaro, I'd suggest you open a PR with proposed changes against https://github.com/fujitsu/xbyak_aarch64 and continue iterating.

**Closed** 2023-03-29 17:25 UTC
Labels: question
