### ISSUE TITLE
avoiding a very slow binary operation

### ISSUE THREAD

**Issue by dagdoron** [oneapi-src/oneDNN#1679] opened 2023-07-04 12:54 UTC
I am trying to implement the following:
I have two S8 sources I need to multiply each by a corresponding shifts F32 (1 / 2^x) and then multiply by another S8 multiplier (both with broadcast)
I have implemented it with two binary operations with post ops
1)	Multiply src0 and shift0 
     a.	post op multiply by mul0 
     b.	tmp0 result is s32
2)	Multiply src1 and shift1 
     a.	Post op multiply by mul1
     b.	Post op add tmp0 
     c.	        Result is s8

However, the first binary is executed in ref which in real life example take very long  (450x ).
For example:
onednn_verbose,exec,cpu,binary,ref:any,undef,src_s8::blocked:acdb::f0 src_f32::blocked:acdb::f0 dst_s32::blocked:acdb::f0,attr-scratchpad:user attr-post-ops:binary_mul:s8:2 ,alg:binary_mul,1x256x64x64:1x256x1x1,155.122
onednn_verbose,exec,cpu,binary,jit:uni,undef,src_s8::blocked:acdb::f0 src_f32::blocked:acdb::f0 dst_s8:a:blocked:acdb::f0,attr-scratchpad:user attr-post-ops:binary_mul:s8:2+binary_add:s32:14:acdb ,alg:binary_mul,1x256x64x64:1x256x1x1,0.296875

is there a way to avoid the slow ref implementation?

here is a small working example over v3.2

#include <vector>
#include <map>
#include <algorithm>

#include "oneapi/dnnl/dnnl.hpp"

using namespace dnnl;
using tag = memory::format_tag;
using dt = memory::data_type;

void simple_net_int8(int size) {
    DNNL_API dnnl_set_verbose(2);
    set_max_cpu_isa(cpu_isa::avx512_core);

    auto eng = engine(engine::kind::cpu, 0);
    stream s(eng);

    // input and output dimensions
    memory::dims dims = {1, size, size, size};
    memory::dims mul_dims = {1, size, 1, 1};

    std::vector<int8_t> src0(512, 1);
    std::vector<int8_t> src1(512, 2);
    std::vector<int8_t> dst(512, 0);

    std::vector<float> shifts0(size, 1.0f);
    std::vector<float> shifts1(size, 1.0f);

    std::vector<int8_t> mul0(size, 1);
    std::vector<int8_t> mul1(size, 1);

    memory::desc mul_md = memory::desc(mul_dims, dt::s8, tag::nhwc);
    memory mul0_memory = memory(mul_md, eng, mul0.data());
    memory mul1_memory = memory(mul_md, eng, mul1.data());

    memory::desc shift_md = memory::desc(mul_dims, dt::f32, tag::nhwc);
    memory shift0_memory = memory(mul_md, eng, mul0.data());
    memory shift1_memory = memory(mul_md, eng, mul1.data());

    // set src to nhwc - we require it in the configure
    memory::desc src0_md = memory::desc(dims, dt::s8, tag::nhwc);
    memory::desc src1_md = memory::desc(dims, dt::s8, tag::nhwc);
    memory::desc dst_md = memory::desc(dims, dt::s8, tag::any);

    post_ops binary_post_ops0;
    post_ops binary_post_ops1; // post-ops for second primitive
    primitive_attr attr0 = primitive_attr();
    primitive_attr attr1 = primitive_attr();
    memory::desc primitive_1_dest_md = memory::desc(dims, dt::s32, tag::nhwc);
    binary_post_ops0.append_binary(algorithm::binary_mul, mul_md);
    attr0.set_post_ops(binary_post_ops0);
    binary::primitive_desc bin0_pd = binary::primitive_desc(eng, algorithm::binary_mul,
            src0_md, shift_md, primitive_1_dest_md, attr0);

    binary_post_ops1.append_binary(algorithm::binary_mul, mul_md);
    binary_post_ops1.append_binary(algorithm::binary_add, primitive_1_dest_md);
    attr1.set_post_ops(binary_post_ops1);
    binary::primitive_desc bin1_pd = binary::primitive_desc(eng, algorithm::binary_mul,
            src1_md, shift_md, dst_md, attr1);

    memory src0_memory = memory(src0_md, eng, src0.data());
    memory src1_memory = memory(src1_md, eng, src1.data());
    memory dst_memory = memory(bin1_pd.dst_desc(), eng, dst.data());

    memory tmp0 = memory({dims, dt::s32, tag::nhwc}, eng);
    std::unordered_map<int, memory> arg0;

    // Args for first primitive - Scale Input 1 and save in dsts[1]
    arg0.insert({DNNL_ARG_SRC_0, src0_memory});
    arg0.insert({DNNL_ARG_SRC_1, shift0_memory});
    arg0.insert({DNNL_ARG_DST, tmp0});
    arg0.insert({DNNL_ARG_ATTR_MULTIPLE_POST_OP(0) | DNNL_ARG_SRC_1, mul0_memory});

    //Args for second pirmitive - Scale Input 2 and save and add to the first input
    memory tmp1 = memory({dims, dt::s32, tag::nhwc}, eng);
    std::unordered_map<int, memory> arg1;

    arg1.insert({DNNL_ARG_SRC_0, src1_memory});
    arg1.insert({DNNL_ARG_SRC_1, shift1_memory});
    arg1.insert({DNNL_ARG_DST, tmp1});
    arg1.insert({DNNL_ARG_ATTR_MULTIPLE_POST_OP(0) | DNNL_ARG_SRC_1, mul1_memory});
    arg1.insert({DNNL_ARG_ATTR_MULTIPLE_POST_OP(1) | DNNL_ARG_SRC_1, tmp0});

    binary binary0_prim = binary(bin0_pd);
    binary0_prim.execute(s, arg0);
    s.wait();

    binary binary1_prim = binary(bin1_pd);
    binary1_prim.execute(s, arg1);
    s.wait();

}

int main(int argc, char **argv) {

    int size = 8;
    simple_net_int8(size);
    return 0;
}

**Comment by dagdoron** [comment] 2023-07-04 13:02
looks like something went wrong with the code sample 

missing in the firs line of the function : void simple_net_int8(int size) {

**Comment by igorsafo** [comment] 2023-07-06 19:03
Hi @dagdoron , Sorry for the late response, I was trying to understand what happens in the example and how it can be mitigated. The issue is binary primitive is optimized for operations where `src0` and `dst` memory descriptors are similar (have the same tag, the same data type) while `src1` can be broadcasted or have another data type. In your case `src0` and `dst` have different data types so binary dispatches into reference implementation.

For (De-)quantization oneDNN uses reorder primitive which have optimized implementations for reorders between different data types. So one of potential solutions would be to use reorder with src scale (it must be in f32) to dequantize data from s8 to f32. Then separately use binary primitive to complete dequantization.

I see that your dequantization involeves shift and scale, but why do you multiply on shift and not add/subtract it? This prevents from implementing whole dequantization as a single reorder. Here is quantization that is supported by oneDNN: https://oneapi-src.github.io/oneDNN/dev_guide_attributes_quantization.html

**Comment by dagdoron** [comment] 2023-07-06 20:02
Hi @igorsafo 
Thanks, 
I'll try reorder before the binary and let you know if that helped
We are using a slightly different dequantization schema, where the shifts are actually bit shifts and we try to emulate the HW by multiplying by 2^x instead of shifting

**Comment by dagdoron** [comment] 2023-07-10 12:46
Hi @igorsafo 

I've changed src0 to be s32 in accordance with tmp0 type so now src0 and dst have the same type

e.g.
std::vector<int32_t> src0(512, 1);
memory::desc src0_md = memory::desc(dims, dt::s32, tag::nhwc);

the execution still falls back to ref
onednn_verbose,create:cache_miss,cpu,binary,ref:any,undef,src_s32::blocked:acdb::f0 src_f32::blocked:acdb::f0 dst_s32::blocked:acdb::f0,attr-post-ops:binary_mul:s8:2 ,alg:binary_mul,1x8x8x8:1x8x1x1,0.104004
onednn_verbose,exec,cpu,binary,ref:any,undef,src_s32::blocked:acdb::f0 src_f32::blocked:acdb::f0 dst_s32::blocked:acdb::f0,attr-post-ops:binary_mul:s8:2 ,alg:binary_mul,1x8x8x8:1x8x1x1,1.11914

**Comment by igorsafo** [comment] 2023-07-10 20:16
Yes, I was able to reproduce it. Another limitation of JIT I found is it doesn't support s32 data type. I will create an internal ticket to track this issue.

**Comment by igorsafo** [comment] 2023-07-10 23:15
@dagdoron s32 support is in progress for jit implementation.

A separate question: Would shift operation serve better or binary mul with s32 support is enough for your use cases?

**Comment by dagdoron** [comment] 2023-07-11 05:57
@igorsafo 
s32 would be good enough, however if you can support shifts it would be the best, it would save us some cycles converting them and I guess integer shifts may be faster than float mul

**Comment by igorsafo** [comment] 2023-07-11 19:22
@dagdoron Could you please try the latest version of `master` branch? The support is added in 46135fd

**Comment by dagdoron** [comment] 2023-07-12 09:52
@igorsafo - Thanks for the fast respond and fix

With this commit, the binary is executing the jit version

onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_s8::blocked:acdb::f0 dst_s32::blocked:acdb::f0,,,1x256x128x128,0.911133
onednn_verbose,exec,cpu,binary,jit:uni,undef,src_s32::blocked:acdb::f0 src_f32::blocked:acdb::f0 dst_s32::blocked:acdb::f0,attr-scratchpad:user attr-post-ops:binary_mul:s8:2 ,alg:binary_mul,1x256x128x128:1x256x1x1,7.27001
onednn_verbose,exec,cpu,binary,jit:uni,undef,src_s8::blocked:acdb::f0 src_f32::blocked:acdb::f0 dst_s8:a:blocked:acdb::f0,attr-scratchpad:user attr-post-ops:binary_mul:s8:2+binary_add:s32:14:acdb ,alg:binary_mul,1x256x128x128:1x256x1x1,1.86791

**Comment by igorsafo** [comment] 2023-07-12 15:49
Great to know! I added an internal request about shift operation, but there is no guarantee it will be implemented until we have more use cases and users, because it will require much more resources on our side to implement and maintain it.

I am closing this issue since the performance issue is fixed. Feel free to re-open or create a separate issue if you have any other requests.

**Closed by igorsafo** 2023-07-12 15:49 UTC
Labels: enhancement, question
