### ISSUE TITLE
How to get cout working inside library?

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1102] opened 2021-06-24 16:32 UTC
Hi,
I put some `cout` commands inside library code and compiled it again. When I run an example using the library I can not find my `cout` messages on standard output. Just `cout` commands inside application code is working. How should I resolve it?

**Comment by igorsafo** [comment] 2021-06-24 16:42
Hi @kokhazade ,
oneDNN doesn't have any print suppressing mechanisms, so it should print everything you put into the library.
- Where did you put `cout` commands? It is possible that execution didn't reach places where `cout`s were added.
- How did you rebuilt the library?
- Are you sure that the application uses the same exact library and doesn't point to another version of oneDNN?

**Comment by kokhazade** [comment] 2021-06-24 17:07
Hi @igorsafo ,
Thanks for your response. I rechecked the process and found while I don't run `make install` after compiling library, it links my application to previous library has been installed on `/usr/local/lib/ ` even if I pass my new library path when I compile library using `-L` option. So, it resolved.

**Comment by igorsafo** [comment] 2021-06-24 21:55
Closing the issue, since the problem seems to be resolved and the root cause is a missing `make install`.

**Closed by igorsafo** 2021-06-24 21:55 UTC
Labels: question
