### ISSUE TITLE
Documentation for mklDNN installation is out of date

### ISSUE THREAD

**Issue by krishna-kumar-netizen** [oneapi-src/oneDNN#1254] opened 2022-01-28 10:15 UTC
# Summary
MKLDNN fails a few tests (present in the build directory) after installation. The output of the tests is attached. 
[
[test_out_28-01-21.txt](https://github.com/oneapi-src/oneDNN/files/7957773/test_out_28-01-21.txt)
](url)

**Comment by vpirogov** [comment] 2022-01-28 16:30
@krishna-kumar-netizen, we need more details on the configuration and environment you are using to investigate this. See the list below.

# Version
Report oneDNN version and githash. Version information is printed to stdout
in [verbose mode](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html).

# Environment
oneDNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
* OS version (`uname -a`)
* Compiler version (`gcc --version`)
* CMake version (`cmake --version`)
* Build command line
* CMake output log

**Comment by krishna-kumar-netizen** [comment] 2022-01-31 13:12
**Version Information** - Attached as version_details.txt 

**CPU - details** -  Attached as cpu_details

**OS Version** - Linux lotusdew-xilinx 5.8.0-050800-generic #202008022230 SMP Sun Aug 2 22:33:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Compiler-Version** - gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**Build command line**   -  `mkdir -p ~/mkl-dnn/build && cd ~/mkl-dnn/build && cmake .. && ~/mkl-dnn/build/make`

**Cmake ouput log**  -  Attached as Cmake_output_log

Files attached - [Click Here](https://drive.google.com/drive/folders/1exYoG3Pj-nCczlTqt7xmzkD55xSZ8Nkl?usp=sharing)

**Comment by mgouicem** [comment] 2022-01-31 13:29
Hi @krishna-kumar-netizen , could you share the commit hash you are testing? You could get it using `git rev-parse HEAD`, or by running the test by setting the `ONEDNN_VERBOSE=1` environment variable. 
Thank you.

**Comment by krishna-kumar-netizen** [comment] 2022-01-31 14:37
The commit hash is b73e8cba6b0fa4fcdc4baf85dd58c5a218d6d37d

**Comment by vpirogov** [comment] 2022-01-31 17:18
Thanks, @krishna-kumar-netizen. I checked this revision on Ubuntu 20.04 box with GCC 9.3 and processor with Intel AVX2 instructions support, but the issue did not reproduce. Looks like there's additional factor in your environment affecting the application behavior.

**Comment by vpirogov** [comment] 2022-02-09 17:45
Closing as observed behavior is not reproducible. Feel free to reopen with additional data.

**Closed by vpirogov** 2022-02-09 17:45 UTC
Labels: sighting
