### ISSUE TITLE
Why flags of dnnl_memory_extra_desc_t is valued as 3 

### ISSUE THREAD

**Issue by lisa0314** [oneapi-src/oneDNN#691] opened 2020-04-08 06:37 UTC
When I obtain the memory descriptor of weights named `weights_md` for conv primitive using `dnnl_primitive_desc_query_md`. Since the source and weights for conv are both s8, I expect the value of `flags` of `dnnl_memory_extra_desc_t` of `weights_md` should be 1 as defined:
`typedef enum {`
   ` dnnl_memory_extra_flag_none = 0x0U,`
   ` dnnl_memory_extra_flag_compensation_conv_s8s8 = 0x1U,`
   ` dnnl_memory_extra_flag_scale_adjust = 0x2U,`
    `dnnl_memory_extra_flag_gpu_rnn_u8s8_compensation = 0x4U,`
`} dnnl_memory_extra_flags_t;`

However, I find the value of flags is valued as 3 and I can't figure out what 3 means.
Hardware:
Intel AVX-512 with Intel DL Boost

**Comment by igorsafo** [comment] 2020-04-08 08:05
Hi @lisa0314. flags = 3 means that weight_md contains both compensation_conv_s8s8 & scale_adjust (0x1U | 0x2U). scale_adjust is used to overcome the potential overflow issue. However it is equal to 1.0 and not used when Intel AVX-512 with Intel DL Boost is available.
There is a very detailed explanation in the dev guide [Int8 Computation Aspects](https://oneapi-src.github.io/oneDNN/dev_guide_int8_computations.html):
"_The source is treated as X_s8, which would be shifted during the execution. The compensation is precomputed by a reorder during quantization of the weights, and embedded into them. **Finally, when the Intel AVX2 or Intel AVX512 Instruction Set is used the reorder additionally scales the weights by 0.5 to overcome the potential overflow issue.** During the convolution execution, the result would be re-scaled back. This rescaling introduces an error that might insignificantly affect the inference accuracy (compared to a platform with the Intel DL Boost Instruction Set)._"

**Comment by lisa0314** [comment] 2020-04-08 10:28
@igorsafo Thanks for your detailed explanation! I got it!

**Comment by lisa0314** [comment] 2020-04-08 10:40
@igorsafo I also have another question for "_The compensation is precomputed by a reorder during quantization of the weights, and embedded into them_". Does precompute process could only be completed during quantization? Since I have acquired the quantized model using caffe2 and I could got the quantized weights(s8) directly. Could I complete the precompute process using reorder without quantization?

**Comment by igorsafo** [comment] 2020-04-08 20:48
@lisa0314 , yes, DNNL reorder supports adding compensation without quantization (s8 -> s8).

**Comment by lisa0314** [comment] 2020-04-09 03:25
I encountered with a reorder fail when I create a record primitive descriptor using `dnnl_reorder_primitive_desc_create` for recording weights of s8s8conv primitive(adding compensation). 
The input memory for reorder -  type: s8, memory_format_tag_t: dnnl_ohwi, dnnl_memory_extra_flags_t = dnnl_memory_extra_flag_none;
The output memory for reorder - type: s8, memory_format_tag_t is the optimized memory format choosing by conv primitive itself, dnnl_memory_extra_flags_t = dnnl_memory_extra_flag_compensation_conv_s8s8;
Howvere, I got the retrun value of ` UNIMPLEMENTED`. I want to make sure if I miss something or it's a bug for record. @igorsafo could you share your opinion?

**Comment by igorsafo** [comment] 2020-04-09 07:56
@lisa0314 , Could you please provide a reproducer & shapes of your convolution? Reorder you described seems correct.

**Comment by igorsafo** [comment] 2020-04-09 07:57
@lisa0314 , Could you please provide a reproducer & shapes of your convolution? Reorder you described seems correct.

**Comment by lisa0314** [comment] 2020-04-09 12:28
- source 
type: s8, dims: [1,2,3,1], memory_format_tag= dnnl_nhwc;

- weights
type:s8, dims: [3,2,1,1] memory_format_tag = dnnl_ohwi

- bias
type:int32 dims: [3] memory_format_tag = dnnl_x;

-output
type: s8, dims: [1,3,3,1] memory_format_tag = dnnl_nhwc

**Comment by lisa0314** [comment] 2020-04-10 03:43
@igorsafo I confirm that the reorder primitive can't support the reorder I described above. Since I decomposed the reorder of weights(s8) into two steps:
1. reorder from dnnl_nhwc to plain 4D tensor dnnl_abcd;
2. reorder from dnnl_abcd to the optimized format which conv primitive choose.
it passed ! Could you please share your opinion?

**Comment by igorsafo** [comment] 2020-04-10 04:04
@lisa0314 Thanks for the update! Weights usually are described using oihw or hwio formats. nhwc is similar to ohwi, and this format is not supported by s8->s8 reorder: https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/cpu_reorder.cpp#L490

Is it possible to use oihw or hwio as a reference format for weights in your application?

**Comment by lisa0314** [comment] 2020-04-10 07:20
@igorsafo I will try it! Thanks!

**Comment by vpirogov** [comment] 2020-04-17 00:10
Closing as the question seems to be addressed. Feel free to reopen or submit a new one if you have any further questions.

**Closed by vpirogov** 2020-04-17 00:10 UTC
Labels: question
