### ISSUE TITLE
Information about OMP Settings

### ISSUE THREAD

**Issue by ratan** [oneapi-src/oneDNN#727] opened 2020-05-07 09:12 UTC
**1.** I checked out oneDNN v1.2

**2.** Build it using clang
```
export CC=clang and export CXX=clang++
mkdir -p build && cd build && cmake ..
make -j
sudo make install
```

**3.** modified getting_started.cpp to add a print as first line inside main() function
```
(base) ratan@dattonaxq1648:~/my_work/oneDNN/examples$ git diff
diff --git a/examples/getting_started.cpp b/examples/getting_started.cpp
index 2376013eb..3c43dab91 100644
--- a/examples/getting_started.cpp
+++ b/examples/getting_started.cpp
@@ -469,6 +469,7 @@ void getting_started_tutorial(engine::kind engine_kind) {
 /// @snippet getting_started.cpp Main
 // [Main]
 int main(int argc, char **argv) {
+    **std::cout << "Start of getting_started code\n";**
     int exit_code = 0;
```

**4.** export these env variables for verbose
```
export KMP_AFFINITY=verbose
export OMP_DISPLAY_ENV=TRUE
export KMP_SETTINGS=TRUE
```

**5.** build examples/getting_started.cpp
```
clang++ -std=c++11 getting_started.cpp -o bin/getting_started_cpp -L/usr/local/lib -ldnnl
```

**6.** Run above test
```
(base) ratan@dattonaxq1648:~/my_work/oneDNN/examples$ ./bin/getting_started_cpp

User settings:

   KMP_AFFINITY=verbose
   KMP_SETTINGS=TRUE
   OMP_DISPLAY_ENV=TRUE

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=384
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=200
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=false
   KMP_ENABLE_TASK_THROTTLING=true
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_FORKJOIN_FRAMES=true
   KMP_FORKJOIN_FRAMES_MODE=3
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_ITT_PREPARE_DELAY=0
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER_PATTERN='hyper,hyper'
   KMP_REDUCTION_BARRIER='1,1'
   KMP_REDUCTION_BARRIER_PATTERN='hyper,hyper'
   KMP_SCHEDULE='static,balanced;guided,iterative'
   KMP_SETTINGS=true
   KMP_SPIN_BACKOFF_PARAMS='4096,100'
   KMP_STACKOFFSET=64
   KMP_STACKPAD=0
   KMP_STACKSIZE=8M
   KMP_STORAGE_MAP=false
   KMP_TASKING=2
   KMP_TASKLOOP_MIN_TASKS=0
   KMP_TASK_STEALING_CONSTRAINT=1
   KMP_TEAMS_THREAD_LIMIT=96
   KMP_TOPOLOGY_METHOD=all
   KMP_USE_YIELD=1
   KMP_VERSION=false
   KMP_WARNINGS=true
   OMP_AFFINITY_FORMAT='OMP: pid %P tid %i thread %n bound to OS proc set {%A}'
   OMP_ALLOCATOR=omp_default_mem_alloc
   OMP_CANCELLATION=false
   OMP_DEFAULT_DEVICE=0
   OMP_DISPLAY_AFFINITY=false
   OMP_DISPLAY_ENV=true
   OMP_DYNAMIC=false
   OMP_MAX_ACTIVE_LEVELS=1
   OMP_MAX_TASK_PRIORITY=0
   OMP_NESTED: deprecated; max-active-levels-var=1
   OMP_NUM_THREADS: value is not defined
   OMP_PLACES: value is not defined
   OMP_PROC_BIND='false'
   OMP_SCHEDULE='static'
   OMP_STACKSIZE=8M
   OMP_TARGET_OFFLOAD=DEFAULT
   OMP_THREAD_LIMIT=2147483647
   OMP_TOOL=enabled
   OMP_TOOL_LIBRARIES: value is not defined
   OMP_WAIT_POLICY=PASSIVE
   KMP_AFFINITY='verbose,warnings,respect,granularity=core,none'


OPENMP DISPLAY ENVIRONMENT BEGIN
   _OPENMP='201611'
  [host] OMP_AFFINITY_FORMAT='OMP: pid %P tid %i thread %n bound to OS proc set {%A}'
  [host] OMP_ALLOCATOR='omp_default_mem_alloc'
  [host] OMP_CANCELLATION='FALSE'
  [host] OMP_DEFAULT_DEVICE='0'
  [host] OMP_DISPLAY_AFFINITY='FALSE'
  [host] OMP_DISPLAY_ENV='TRUE'
  [host] OMP_DYNAMIC='FALSE'
  [host] OMP_MAX_ACTIVE_LEVELS='1'
  [host] OMP_MAX_TASK_PRIORITY='0'
  [host] OMP_NESTED: deprecated; max-active-levels-var=1
  [host] OMP_NUM_THREADS: value is not defined
  [host] OMP_PLACES: value is not defined
  [host] OMP_PROC_BIND='false'
  [host] OMP_SCHEDULE='static'
  [host] OMP_STACKSIZE='8M'
  [host] OMP_TARGET_OFFLOAD=DEFAULT
  [host] OMP_THREAD_LIMIT='2147483647'
  [host] OMP_TOOL='enabled'
  [host] OMP_TOOL_LIBRARIES: value is not defined
  [host] OMP_WAIT_POLICY='PASSIVE'
OPENMP DISPLAY ENVIRONMENT END


OMP: Info #211: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #209: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-95
OMP: Info #156: KMP_AFFINITY: 96 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 2 packages x 24 cores/pkg x 2 threads/core (48 total cores)
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85048 thread 0 bound to OS proc set 0-95
Start of getting_started code
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85049 thread 1 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85051 thread 3 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85050 thread 2 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85052 thread 4 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85053 thread 5 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85054 thread 6 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85055 thread 7 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85056 thread 8 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85057 thread 9 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85059 thread 11 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85058 thread 10 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85060 thread 12 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85061 thread 13 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85062 thread 14 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85063 thread 15 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85064 thread 16 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85066 thread 18 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85065 thread 17 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85067 thread 19 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85068 thread 20 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85069 thread 21 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85070 thread 22 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85071 thread 23 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85072 thread 24 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85074 thread 26 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85073 thread 25 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85075 thread 27 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85076 thread 28 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85077 thread 29 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85078 thread 30 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85079 thread 31 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85080 thread 32 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85081 thread 33 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85082 thread 34 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85083 thread 35 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85084 thread 36 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85085 thread 37 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85086 thread 38 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85087 thread 39 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85088 thread 40 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85089 thread 41 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85090 thread 42 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85091 thread 43 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85092 thread 44 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85093 thread 45 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85095 thread 47 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85094 thread 46 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85096 thread 48 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85097 thread 49 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85098 thread 50 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85099 thread 51 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85101 thread 53 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85100 thread 52 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85102 thread 54 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85103 thread 55 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85105 thread 57 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85104 thread 56 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85106 thread 58 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85107 thread 59 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85108 thread 60 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85109 thread 61 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85110 thread 62 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85111 thread 63 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85112 thread 64 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85113 thread 65 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85114 thread 66 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85115 thread 67 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85116 thread 68 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85117 thread 69 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85119 thread 71 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85118 thread 70 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85120 thread 72 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85121 thread 73 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85122 thread 74 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85123 thread 75 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85125 thread 77 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85124 thread 76 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85126 thread 78 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85127 thread 79 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85128 thread 80 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85129 thread 81 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85130 thread 82 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85131 thread 83 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85132 thread 84 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85133 thread 85 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85135 thread 87 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85134 thread 86 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85136 thread 88 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85137 thread 89 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85138 thread 90 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85139 thread 91 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85140 thread 92 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85141 thread 93 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85142 thread 94 bound to OS proc set 0-95
OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85143 thread 95 bound to OS proc set 0-95
Example passed on CPU.
```
**7.** If we see that thread 0 is created before 1st line in main() is executed.
**OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85048 thread 0 bound to OS proc set 0-95**
**Start of getting_started code**
**OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85049 thread 1 bound to OS proc set 0-95**

Question:
1. What build setting / or run time env variable to use so that thread bounds happens after entering main()
Something like this:
**Start of getting_started code**
**OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85048 thread 0 bound to OS proc set 0-95**
**OMP: Info #249: KMP_AFFINITY: pid 85048 tid 85049 thread 1 bound to OS proc set 0-95**

**Comment by vpirogov** [comment] 2020-05-07 19:46
Hi @ratan,

This seems to be related to LLVM OpenMP implementation behavior rather than oneDNN. You will more likely to get answer in [stackoverflow](https://stackoverflow.com/questions/tagged/openmp).

One thing you might try is 

> std::cout << "Start of getting_started code\n" **<< std::flush**;

to make sure that your line is printed immediately instead of being buffered.

**Comment by ratan** [comment] 2020-05-08 01:55
[oneDNN_v1.2_example_details.txt](https://github.com/oneapi-src/oneDNN/files/4596610/oneDNN_v1.2_example_details.txt)

Changed the line as suggested so that it is printed immediately instead of being buffered:
**std::cout << "Start of getting_started code\n" << std::flush;**

Same behavior. Enabled DNNL_VERBOSE and thread 0 is created before 1st line in main() is executed.

**OMP: Info #211: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #209: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-95
OMP: Info #156: KMP_AFFINITY: 96 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 2 packages x 24 cores/pkg x 2 threads/core (48 total cores)
OMP: Info #249: KMP_AFFINITY: pid 6193 tid 6193 thread 0 bound to OS proc set 0-95
Start of getting_started code
dnnl_verbose,info,DNNL v1.2.0 (commit 75d0b1a7f3586c212e37acebbb8acd221cee7216)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX2
dnnl_verbose,info,gpu,runtime:none
OMP: Info #249: KMP_AFFINITY: pid 6193 tid 6194 thread 1 bound to OS proc set 0-95**

**Comment by rsdubtso** [comment] 2020-05-08 05:57
Hi @vpirogov and @ratan. I tried following @vpirogov's advice and I consistently have _'Start of getting_started code'_ printed as the first line before all the KMP settings. There must be something else going on. I would suggest reproducing the issue with a simple OpenMP-only test. Otherwise, this does not really look oneDNN-related...

**Comment by ratan** [comment] 2020-05-08 06:37
@rsdubtso You are getting 'Start of getting_started code'  with Intel MP or openMP? Is this same behavior with openMP too your side?

**Comment by rsdubtso** [comment] 2020-05-08 13:58
@ratan : I am using clang 9.0.1 and its OpenMP library. I've tested this on Ubuntu 20.04 and RHEL 7.5.

**Comment by vpirogov** [comment] 2020-05-08 18:05
I wasn't able to reproduce reported behavior either with clang 3.8.1 and clang 7.0.

**Comment by ratan** [comment] 2020-05-09 10:03
[simple_test.txt](https://github.com/oneapi-src/oneDNN/files/4603178/simple_test.txt)
[simple_test_no_dnnl_linked.txt](https://github.com/oneapi-src/oneDNN/files/4603180/simple_test_no_dnnl_linked.txt)
[simple_test_dnnl_linked.txt](https://github.com/oneapi-src/oneDNN/files/4603181/simple_test_dnnl_linked.txt)

I tried to create a simple test (cpp file renamed as simple_test.txt).
When it is compiled simply: clang++ -std=c++11 simple_test.cpp -o bin/simple_test
then output is simple_test_no_dnnl_linked.
When same test is compiled and linked with dnnl:
clang++ -std=c++11 simple_test.cpp -o bin/simple_test -L/usr/local/lib -ldnnl 
then output is simple_test_dnnl_linked.txt

When dnnl is linked to sample test, the openMP binding policy is applied before main() , so we see:
```
OMP: Info #249: KMP_AFFINITY: pid 62796 tid 62796 thread 0 bound to OS proc set 0,48
Start of simple_test code
```
I had asked the question in stackoverflow and i am trying to find out how to make openMP binding policy is applied when the first OpenMP parallel region is created:
[stackoverflow](https://stackoverflow.com/questions/61672131/omp-settings-issue#comment109127058_61672131)

**Comment by ratan** [comment] 2020-05-09 10:07
This comment seems more important from stackoverflow:
_Things that execute before main() are DSO (library) constructors and constructors of static C++ objects. The former you can find looking for __attribute__((constructor)) in the function definition. The later are objects defined in the global scope or static class members_

**Comment by rsdubtso** [comment] 2020-05-09 17:05
What puzzles me is that I cannot reproduce this. Can you provide exact OS name and version and clang version?

**Comment by emfomenk** [comment] 2020-05-09 17:18
Could it be because of this
https://github.com/oneapi-src/oneDNN/blob/6f826747c48b973029441294c834bfe1308d2735/src/cpu/jit_avx512_common_convolution_winograd.cpp#L49
and this
https://github.com/oneapi-src/oneDNN/blob/6f826747c48b973029441294c834bfe1308d2735/src/cpu/cpu_isa_traits.hpp#L199
?

**Comment by rsdubtso** [comment] 2020-05-10 01:34
Good catch! Yes, I think that there are a number of globals that we have in the library that cause this. I would like to reproduce this to find them all.

**Comment by ratan** [comment] 2020-05-10 13:09
@emfomenk Thank you so much. That is a good catch. @rsdubtso I am building in Ubuntu OS 18.04. If i get the list of objects defined in the global scope or static class member ((or command to find it ), it will really help me. I am particularly interested in oneDNN v1.3. Since i didnt get expected behavior, i tried with oneDNN v.1.2.2, v1.2.1, v1.2 etc. Really appreciate your help!

**Comment by rsdubtso** [comment] 2020-05-11 01:37
Thanks @ratan, but I could not reproduce this in a Ubuntu 18.04 VM. I've put a breakpoint on the write syscall under GDB and the first thing the test is trying to write is 'Start of getting_started code':

```
$ OMP_DISPLAY_ENV=TRUE KMP_SETTINGS=TRUE KMP_AFFINITY=verbose gdb ./a.out
Reading symbols from ./a.out...(no debugging symbols found)...done.
(gdb) catch syscall write
Catchpoint 1 (syscall 'write' [1])
(gdb) r
Starting program: /home/rsdubtso/work/ml/mkl-dnn/mkl-dnn/build/a.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Catchpoint 1 (call to syscall write), 0x00007ffff55ef154 in __GI___libc_write (fd=1, buf=0x62d450, nbytes=30) at ../sysdeps/unix/sysv/linux/write.c:27
27      ../sysdeps/unix/sysv/linux/write.c: No such file or directory.
(gdb) print ((char *)buf)
$1 = 0x62d450 "Start of getting_started code\n"
```

Can you please provide:
* Output of `clang --version`
* Output of `ldd <whatever binary you link with dnnl>`
* Full CMake command line and output

**Comment by rsdubtso** [comment] 2020-05-11 02:44
Moreover, a breakpoint put at `omp_get_num_threads()` is not triggered before the syscall catchpoint for `write`, which suggests that there's something else going on...

@ratan: can you please show your environment too (removing anything that is sensitive)?

**Comment by ratan** [comment] 2020-05-12 11:02
[oneDNN_v1.3_global_var_with_func_call.txt](https://github.com/oneapi-src/oneDNN/files/4615095/oneDNN_v1.3_global_var_with_func_call.txt)

With clang 9.0.0 and its OpenMP library oneDNN v1.2, i get old behavior too. I am using priority clang 9.0.0 (modified by our team), and issue is reproducible (new behaviour). I am able to fix it by changing global variable which was getting initialized by calling functions.
E.g. L1_cache_size in src/cpu/jit_avx512_common_conv_winograd_kernel_f32.cpp

`
-unsigned int L1_cache_size = get_cache_size(1, true);
+unsigned int L1_cache_size() {
+    return get_cache_size(1, true);
+}
+unsigned int L2_cache_size() {
+   return get_cache_size(2, true);
`
Converting these global variables to functions calls in below files helped to get the old behaviour;
src/cpu/jit_avx512_common_conv_kernel.cpp
src/cpu/jit_avx512_common_conv_winograd_kernel_f32.cpp
src/cpu/jit_avx512_common_convolution_winograd.cpp
src/cpu/jit_avx512_core_f32_wino_conv_4x3_kernel.cpp
I have attached the patch with fixed my issue. Thanks for all the help.
@emfomenk you pointer really helped.

**Comment by rsdubtso** [comment] 2020-05-12 14:24
@ratan: do you need this in the upstream or you are fine with maintaining your own patches? I don't think this is necessary for 1.4 and later versions as the implementation of `get_cache_size()` changed so that it no longer calls `dnnl_get_max_threads()`.

**Comment by ratan** [comment] 2020-05-13 05:03
@rsdubtso so get_cache_size was calling dnnl_get_max_threads() during global function initialization and due to that in my clang version it causes OMP policy binding to be applied before main() is called. However it is not reproducible in all clang version. As you mentioned 1.4 and later doesnt have this issue, but it someone is using 1.3, they may face this issue. So you may upstream it, if you want. I will maintain my own patch. Thanks for all the supports

**Comment by rsdubtso** [comment] 2020-05-13 05:06
Understood. Thanks for the response. I'll close this then since it requires a custom clang (although I agree that it is a bad idea to call `omp_get_num_threads()` to initialize a global).

**Closed by rsdubtso** 2020-05-13 05:06 UTC
Labels: question
