### ISSUE TITLE
DevCloud oneDNN getting started

### ISSUE THREAD

**Issue by RushivArora** [oneapi-src/oneDNN#744] opened 2020-06-05 20:19 UTC
Hello,

I am running the getting-started.cpp on devcloud using the command oneapi-cli in my devcloud terminal. I am running it via the jupyter notebook and am getting a lot of errors. It seems like the source given for oneapi on devcloud doesn't exist (is it possibly changed?)

The code is: %env ONEAPI_INSTALL=/home/intel/intel/inteloneapi/

I have manually traced this path and cannot find it either. Could I get some help on this?

**Comment by vpirogov** [comment] 2020-06-05 21:44
+@louie-tsai, @nathan-greeneltch-intel

**Comment by louie-tsai** [comment] 2020-06-05 22:03
Hello

The source is under /opt/intel/inteloneapi/oneDNN/latest/cpu_dpcpp_gpu_dpcpp/examples.

For compilation on DevCloud console, could you try to follow below README?
https://github.com/intel/BaseKit-code-samples/tree/master/oneDNN/oneDNN_Getting_Started

For getting started, there is a jupyter notebook for users and it should be better starting point for you to try samples on DevCloud.
Here is the jupyter notebook link, and you will also get the notebook via oneapi-cli.
https://github.com/intel/BaseKit-code-samples/blob/master/oneDNN/oneDNN_Getting_Started/oneDNN_Getting_Started.ipynb

After downloading it, you can easily open it on DevCloud and run through it 

![jnotebook](https://user-images.githubusercontent.com/21761437/83925750-cf899c80-a73c-11ea-9a0d-0db4440a5632.JPG)

Once you finish Getting Started,  I would suggest you to try below notebook as next step.
https://github.com/intel/BaseKit-code-samples/blob/master/oneDNN/oneDNN_CNN_INFERENCE_FP32/oneDNN_CPU2GPU_Porting.ipynb

thanks

**Comment by RushivArora** [comment] 2020-06-05 22:38
@louie-tsai  I was using the jupyter notebook in devcloud for this project. Would you happen to know what is causing this issue in Jupyter? 

I went to oneapi-cli and selected the getting started project for oneDNN.

**Comment by vpirogov** [comment] 2020-06-10 22:47
Hi @RushivArora,

The default installation path in the getting started Jupyter notebook indeed points to to `/home/intel/intel/inteloneapi`. To run this notebook on oneAPI DevCloud you need to update it to `/opt/intel/inteloneapi`. I would expect the default value in the notebook points to the default oneAPI installation location, like it's done in CPU2GPU notebook. Thank you for the report.

**Comment by vpirogov** [comment] 2020-06-10 23:54
The issue is transferred to oneAPI samples.

**Closed by vpirogov** 2020-06-10 23:54 UTC
Labels: sighting
