### ISSUE TITLE
how to build oneDNN v0.20.6

### ISSUE THREAD

**Issue by ratan** [oneapi-src/oneDNN#686] opened 2020-04-06 03:14 UTC
I am able to build oneDNN version v1.2 or v1.3 using these commands:

mkdir -p build && cd build && cmake ..
#Build the library:
make -j
#Build the documentation:
make doc
#Install the library, headers, and documentation:
sudo make install

However when i am trying to build v0.20.6 with same command, i am getting error.
Is there different command to build v0.20.6?

**Comment by rsdubtso** [comment] 2020-04-06 03:43
Which error are you getting?

**Comment by ratan** [comment] 2020-04-06 05:00
(base) amd@localhost:~/ratan/mkl-dnn$ mkdir -p build && cd build && cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- Detecting Intel(R) MKL: trying mklml_intel
-- Detecting Intel(R) MKL: trying mklml_gnu
-- Detecting Intel(R) MKL: trying mklml
-- Detecting Intel(R) MKL: trying mkl_rt
CMake Warning at cmake/MKL.cmake:295 (message):
  Intel(R) MKL not found.  Some performance features may not be available.
  Please run scripts/prepare_mkl.sh to download a minimal set of libraries or
  get a full version from https://software.intel.com/en-us/intel-mkl
Call Stack (most recent call first):
  cmake/OpenMP.cmake:25 (include)
  CMakeLists.txt:76 (include)


-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- OpenMP lib: /usr/lib/x86_64-linux-gnu/libiomp5.so
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- VTune profiling environment is unset
-- Found Git: /usr/bin/git (found version "2.17.0")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/amd/ratan/mkl-dnn/build


(base) amd@localhost:~/ratan/mkl-dnn/build$ make -j
Scanning dependencies of target mkldnn_gtest
Scanning dependencies of target mkldnn
[  0%] Building CXX object tests/gtests/gtest/CMakeFiles/mkldnn_gtest.dir/src/gtest-all.cc.o
[  0%] Building CXX object src/CMakeFiles/mkldnn.dir/common/convolution_pd.cpp.o
[  1%] Building CXX object src/CMakeFiles/mkldnn.dir/common/lrn.cpp.o
[  1%] Building CXX object src/CMakeFiles/mkldnn.dir/common/convolution.cpp.o
[  2%] Building CXX object src/CMakeFiles/mkldnn.dir/common/memory_desc_wrapper.cpp.o
[  2%] Building CXX object src/CMakeFiles/mkldnn.dir/common/batch_normalization.cpp.o
[  2%] Building CXX object src/CMakeFiles/mkldnn.dir/common/pooling.cpp.o
[  2%] Building CXX object src/CMakeFiles/mkldnn.dir/common/primitive.cpp.o
[  3%] Building CXX object src/CMakeFiles/mkldnn.dir/common/primitive_desc.cpp.o
[  3%] Building CXX object src/CMakeFiles/mkldnn.dir/common/primitive_attr.cpp.o
[  3%] Building CXX object src/CMakeFiles/mkldnn.dir/common/query.cpp.o
[  3%] Building CXX object src/CMakeFiles/mkldnn.dir/common/primitive_iterator.cpp.o
[  4%] Building CXX object src/CMakeFiles/mkldnn.dir/common/engine.cpp.o
[  4%] Building CXX object src/CMakeFiles/mkldnn.dir/common/memory.cpp.o
[  4%] Building CXX object src/CMakeFiles/mkldnn.dir/common/eltwise.cpp.o
[  5%] Building CXX object src/CMakeFiles/mkldnn.dir/common/shuffle.cpp.o
[  5%] Building CXX object src/CMakeFiles/mkldnn.dir/common/inner_product.cpp.o
[  5%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/bfloat16_utils.cpp.o
[  5%] Building CXX object src/CMakeFiles/mkldnn.dir/common/verbose.cpp.o
[  5%] Building CXX object src/CMakeFiles/mkldnn.dir/common/deconvolution.cpp.o
[  5%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_engine.cpp.o
[  7%] Building CXX object src/CMakeFiles/mkldnn.dir/common/reorder.cpp.o
[  7%] Building CXX object src/CMakeFiles/mkldnn.dir/common/mkldnn_debug.cpp.o
[  7%] Building CXX object src/CMakeFiles/mkldnn.dir/common/stream.cpp.o
[  8%] Building CXX object src/CMakeFiles/mkldnn.dir/common/utils.cpp.o
[  8%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_batch_normalization_utils.cpp.o
[  8%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_concat.cpp.o
[  8%] Building CXX object src/CMakeFiles/mkldnn.dir/common/scratchpad.cpp.o
[  8%] Building CXX object src/CMakeFiles/mkldnn.dir/common/softmax.cpp.o
[  8%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_primitive.cpp.o
[  9%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_barrier.cpp.o
[  9%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/bf16/jit_avx512_core_gemm_bf16bf16f32_kern.cpp.o
[  9%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_sum.cpp.o
[ 10%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/bf16/jit_avx512_core_s16_copy_bn_kern.cpp.o
[ 10%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_reducer.cpp.o
[ 10%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_reorder.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mkldnn.dir/common/rnn.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/bf16/jit_avx512_core_s16_copy_an_kern.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/cpu_memory.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx2_kernel_sgemm_kern.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/bf16/jit_avx512_core_s16_copy_bt_kern.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx2_f32_copy_an_kern.cpp.o
[ 12%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx2_f32_copy_bt_kern.cpp.o
[ 13%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx512_core_f32_copy_an_kern.cpp.o
[ 13%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx512_core_f32_copy_at_kern.cpp.o
[ 13%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx512_common_gemm_f32.cpp.o
[ 14%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx2_f32_copy_bn_kern.cpp.o
[ 14%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx_gemm_f32.cpp.o
[ 15%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx2_f32_copy_at_kern.cpp.o
[ 16%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx512_core_f32_copy_bt_kern.cpp.o
[ 16%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/gemm_utils_f32.cpp.o
[ 16%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/jit_avx512_core_f32_copy_bn_kern.cpp.o
[ 16%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/f32/ref_gemm_f32.cpp.o
[ 16%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/gemm_driver.cpp.o
[ 17%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/gemm.cpp.o
[ 18%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_gemm_s8u8s32_kern.cpp.o
[ 18%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/gemm_info.cpp.o
[ 18%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_kernel_gemv_s8u8s32_kern.cpp.o
[ 18%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_gemv_s8u8s32.cpp.o
[ 19%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_an_kern.cpp.o
[ 19%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_at_kern.cpp.o
[ 19%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/bf16/jit_avx512_core_s16_copy_at_kern.cpp.o
[ 19%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_bn_kern.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_bt_kern.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/simple_gemm_s8s8s32.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_bf16_inner_product.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_convolution.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_1x1_convolution.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_inner_product_utils.cpp.o
[ 20%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_1x1_conv_kernel_f32.cpp.o
[ 21%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_x8s8s32x_inner_product.cpp.o
[ 21%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_x8s8s32x_convolution.cpp.o
[ 22%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_bf16_convolution.cpp.o
[ 23%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_convolution_utils.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_1x1_conv_kernel.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_conv_kernel_f32.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx2_convolution.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_at_kern.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/ref_gemm_s8x8s32.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_convolution_winograd.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_lrn.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_kernel.cpp.o
[ 24%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_conv_winograd_kernel_f32.cpp.o
[ 26%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_bf16_1x1_conv_kernel.cpp.o
[ 25%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_bn_kern.cpp.o
[ 25%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_an_kern.cpp.o
[ 26%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm/s8x8s32/jit_avx512_core_u8_copy_sum_bt_kern.cpp.o
[ 27%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_1x1_convolution.cpp.o
[ 28%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_common_convolution.cpp.o
[ 28%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/gemm_inner_product.cpp.o
[ 28%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_bf16_1x1_convolution.cpp.o
[ 28%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_bf16_convolution.cpp.o
[ 28%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_bf16_conv_kernel.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_fp32_wino_conv_4x3.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_bf16_sum.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_fp32_wino_conv_2x3.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_1x1_convolution.cpp.o
[ 29%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_fp32_wino_conv_4x3_kernel.cpp.o
[ 30%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_convolution.cpp.o
[ 30%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_conv_kernel_f32.cpp.o
[ 30%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_1x1_convolution.cpp.o
[ 31%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_convolution.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_bf16_dw_conv_kernel.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_1x1_conv_kernel.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_dw_conv_kernel_f32.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_batch_normalization_s8.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_sse42_1x1_conv_kernel_f32.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_conv_kernel.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_eltwise.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_avx512_core_x8s8s32x_deconvolution.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_lrn_kernel_f32.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_pooling.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_i8i8_pooling.cpp.o
[ 33%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_pool_kernel.cpp.o
[ 34%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_reorder.cpp.o
[ 35%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/nchw_pooling.cpp.o
[ 35%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_softmax.cpp.o
[ 37%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_lrn.cpp.o
[ 37%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_dw_convolution.cpp.o
[ 37%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_transpose_src_utils.cpp.o
[ 38%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_batch_normalization.cpp.o
[ 38%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_batch_normalization.cpp.o
[ 38%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_convolution.cpp.o
[ 38%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_inner_product.cpp.o
[ 39%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_eltwise.cpp.o
[ 39%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/jit_uni_reorder_utils.cpp.o
[ 39%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ncsp_batch_normalization.cpp.o
[ 39%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/nhwc_pooling.cpp.o
[ 40%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/nspc_batch_normalization.cpp.o
[ 40%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_softmax.cpp.o
[ 40%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_shuffle.cpp.o
[ 40%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_lrn.cpp.o
[ 40%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_gru.cpp.o
[ 41%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_common.cpp.o
[ 41%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_gru_lbr.cpp.o
[ 41%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_deconvolution.cpp.o
[ 42%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_gru.cpp.o
[ 43%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/ref_pooling.cpp.o
[ 43%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/cell_gru_lbr.cpp.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libiomp5.so', needed by 'src/libmkldnn.so.0.20'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 43%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/simple_concat.cpp.o
[ 44%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_rnn.cpp.o
[ 44%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/rnn_utils.cpp.o
[ 45%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/simple_sum.cpp.o
[ 45%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_rnn.cpp.o
[ 45%] Building CXX object src/CMakeFiles/mkldnn.dir/cpu/rnn/ref_postgemm_lstm.cpp.o
[ 46%] Linking CXX static library libmkldnn_gtest.a
[ 46%] Built target mkldnn_gtest
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/mkldnn.dir/all' failed
make[1]: *** [src/CMakeFiles/mkldnn.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rsdubtso** [comment] 2020-04-06 05:09
Thanks. Which Linux distribution is that and  which package does the `/usr/lib/x86_64-linux-gnu/libiomp5.so` belong to if there is such file?

**Comment by ratan** [comment] 2020-04-06 05:39
Ubuntu 18.04 LTS and i guess libomp-dev is the package.

**Comment by rsdubtso** [comment] 2020-04-06 16:01
I cannot reproduce with either with or without the `libomp-dev` installed. Wild guess: did you uninstall the package in between the `cmake` and `make` calls? Because that's the only case when I can reproduce the message above.

**Comment by ratan** [comment] 2020-04-07 05:44
1. I am getting this error of 
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libiomp5.so', needed by 'src/libmkldnn.so.0.20'.  Stop.
all the time of that particular ubuntu desktop.  I didn't uninstall the package in between the cmake and make calls. 
When i am building oneDNN 1.x version, I am not seeing this error.

2. However I tried on different Ubuntu desktop, and i am not seeing this error.

3. I copied all the lib/ includes files generated in step 2 in a folder and trying to compile example  source code in 3rd ubuntu desktop (where i dont want to install onDNN, but use the folder from step 2. Folder name is: home/ratan/my_work/external/dnnlBuild)

I am again getting error libomp.so.5 not found:


(base) ratan@dattonaxq1648:~/my_work/oneDNN/examples$ g++ -std=c++11 simple_net.cpp -I/home/ratan/my_work/external/dnnlBuild/include  -L/home/ratan/my_work/external/dnnlBuild/lib -lmkldnn -o bin/simple_net

/usr/bin/ld: warning: libomp.so.5, needed by /home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so, not found (try using -rpath or -rpath-link)
/home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so: undefined reference to `omp_get_thread_num@VERSION'
/home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so: undefined reference to `omp_get_max_threads@VERSION'
/home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so: undefined reference to `GOMP_barrier@VERSION'
/home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so: undefined reference to `GOMP_parallel@VERSION'
/home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so: undefined reference to `omp_in_parallel@VERSION'
/home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so: undefined reference to `omp_get_num_threads@VERSION'
collect2: error: ld returned 1 exit status
(base) ratan@dattonaxq1648:~/my_work/oneDNN/examples$
---------------------------------------

More inputs:
------------


(base) ratan@dattonaxq1648:~/my_work/external/dnnlBuild$ ls include/
mkldnn_debug.h  mkldnn.h  mkldnn.hpp  mkldnn_types.h  mkldnn_version.h

(base) ratan@dattonaxq1648:~/my_work/external/dnnlBuild$ ls lib/
libmkldnn.so  libmkldnn.so.0  libmkldnn.so.0.20    mkldnn-config.cmake  mkldnn-config-version.cmake  mkldnn-targets.cmake  mkldnn-targets-release.cmake


(base) ratan@dattonaxq1648:~/my_work/oneDNN/examples$ ldd /home/ratan/my_work/external/dnnlBuild/lib/libmkldnn.so
        linux-vdso.so.1 (0x00007fff653bb000)
        libomp.so.5 => not found
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1d91b6e000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1d917d0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1d915b8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1d911c7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1d92dc4000)

**Comment by rsdubtso** [comment] 2020-04-07 18:40
I do not understand what is happening on the first machine. Can you completely remove the build directory and re-build the library?

Does the `attonaxq1648` machine have the `libomp-dev` installed? You also need to have it on the link line `-lomp` as it is a dependency for `libmkldnn.so`.

**Comment by ratan** [comment] 2020-04-09 07:41
I tried to remove build directory and build. same result.
My main concern is not first machine.  How to build on dattonaxq1648 when i have copied lib and include from other machine?
Is there a direct link where i can download just binary release (lib, include, doc) folder for v0.20.6?

**Comment by rsdubtso** [comment] 2020-04-09 21:46
> How to build on dattonaxq1648 when i have copied lib and include from other machine?
Do you have `libomp-dev` installed on `dattonaxq1648`? Did you try specifying `-lomp` on the link line?

> Is there a direct link where i can download just binary release (lib, include, doc) folder for v0.20.6?
No, there are no pre-built binaries.

**Comment by rsdubtso** [comment] 2020-04-15 16:48
Closing as this seems to be an environment problem on the user side.

@ratan : please feel free to reopen if you find a way to reproduce this on any machine, and please feel free to post a solution if you found how to resolve this problem.

**Closed by rsdubtso** 2020-04-15 16:48 UTC
Labels: build, sighting
