### ISSUE TITLE
aarch64: Multiple performance degradations after the migration from v3.1 to v3.2

### ISSUE THREAD

**Issue by EgorDuplensky** [oneapi-src/oneDNN#1691] opened 2023-07-26 13:27 UTC
# Summary
Openvino framework uses oneDNN for both x86 and aarch64 platforms.
After migration from 3.1 to 3.2 version we have noticed significant performance degradation on aarch64 platform for almost all the models.
The following primitives are affected:
* Matmul:
  The root cause is seemed to be the change related to choosing acl primitive implementation.
  In version 3.1 it was possible to use a particular memory format.
  Starting from 3.2 acl primitive implementation is chosen only if user specifies memory::format_tag::any for the weights input.
  Because of that matmul primitive always uses gemm implementation, which is significantly slower.
  What is expected: it should be possible to have both options, to specify a particular memory format and to specify memory::format_tag::any without falling back to gemm implementation.

  Note: It seems the same requirement was also forced for inner_product and convolution primitives.
  This also led to big performance degradations. But since we already used  memory::format_tag::any for those primitives,
  the only change required was to enable "experimental_fixed_format_kernels".
  In general it is also not clear why it is not possible to support a particular memory format for those primitives as well.
* Convolution:
  Almost all the CNN models showed performance degradation with 3.2 version.
  The reason is the drop off acl winograd convolution implementation.
  TBD: add benchdnn examples of performance degradations.

# Version
v3.2

# Environment
* CPU
  sysctl -a | grep machdep.cpu
machdep.cpu.cores_per_package: 8
machdep.cpu.core_count: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
machdep.cpu.brand_string: Apple M1

* OS version (`uname -a`)
Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; RELEASE_ARM64_T8103 arm64
  
* Compiler version (`gcc --version`)
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin22.5.0
Thread model: posix
* CMake version (`cmake --version`)
  cmake version 3.26.4
* CMake output log
* git hash (`git log -1 --format=%H`)
  f1080be59e8eaa053195cd06da833f6515e29a96

# Steps to reproduce
* Matmul performance degradation:
  Execute any matmul kernel configuration with specifying a particular (non-any) memory format for the weights input
* Convolution performance degradation:
   - [ ] TBD: add benchdnn examples

# Observed behavior
TBD: add examples

# Expected behavior
It is expected that:
* For convolution, matmul and inner_product primitive it shouldn't be required to use memory::format_tag::any for the acl primitive implementations.
* For winograd convolution no noticeable performance degradation should happen after the drop of this primitive implementation type.

**Comment by igorsafo** [comment] 2023-07-26 15:43
Thanks for the issue.
Most likely the issue is caused by these changes: https://github.com/oneapi-src/oneDNN/pull/1590 
@nSircombe @jondea Could you please take a look?

**Comment by jondea** [comment] 2023-07-27 08:20
The ACL GEMM based primitive do now require the weights reorder to happen outside of the primitive. I'm looping in @milpuz01 too work out next steps.

**Comment by milpuz01** [comment] 2023-08-02 09:48
Hi @EgorDuplensky, thank you very much for reporting the issue. To help us to validate potential fixes on our side could you please let us know:

1. For `matmul`, could you please let us know what is the flow that you are using to create the primitive. Before running the primitive we expect RHS to be in a specific format which is obtained [here](https://github.com/oneapi-src/oneDNN/blob/c19c62c60be2ecc3ce70e4b0d54ebbcfbe20603f/src/cpu/aarch64/matmul/acl_matmul_utils.cpp#L109) and then we do `reorder` [here](https://github.com/oneapi-src/oneDNN/blob/c19c62c60be2ecc3ce70e4b0d54ebbcfbe20603f/src/cpu/aarch64/matmul/acl_matmul_utils.cpp#L131) based on that information. I guess in your flow you first query what should be the format, do the reorder on your side and then run `matmul`? If so could you please share that flow with us?

2. For CNNs that you are running could you please share few shapes with us so that we can test performance? We have removed Winograd implementation because we didn't have any cases where we see it used and also there was issue when using threadpool scheduler that when configuring ACL for winograd operation we didn't have information what is number of threads that will be used before actually running the operation. For your use case are you using OpenMP or thread pool scheduler?

Many thanks,
Milos.

**Comment by EgorDuplensky** [comment] 2023-08-03 11:28
> Hi @EgorDuplensky, thank you very much for reporting the issue. To help us to validate potential fixes on our side could you please let us know:
> 
> 1. For `matmul`, could you please let us know what is the flow that you are using to create the primitive. Before running the primitive we expect RHS to be in a specific format which is obtained [here](https://github.com/oneapi-src/oneDNN/blob/c19c62c60be2ecc3ce70e4b0d54ebbcfbe20603f/src/cpu/aarch64/matmul/acl_matmul_utils.cpp#L109) and then we do `reorder` [here](https://github.com/oneapi-src/oneDNN/blob/c19c62c60be2ecc3ce70e4b0d54ebbcfbe20603f/src/cpu/aarch64/matmul/acl_matmul_utils.cpp#L131) based on that information. I guess in your flow you first query what should be the format, do the reorder on your side and then run `matmul`? If so could you please share that flow with us?
> 2. For CNNs that you are running could you please share few shapes with us so that we can test performance? We have removed Winograd implementation because we didn't have any cases where we see it used and also there was issue when using threadpool scheduler that when configuring ACL for winograd operation we didn't have information what is number of threads that will be used before actually running the operation. For your use case are you using OpenMP or thread pool scheduler?
> 
> Many thanks, Milos.

Hi,
I propose to stick with oneDNN api when we try to align with the use cases.
1. When user wants to create primitive, oneDNN basically provides two options for the memory formats specification:
   - `any` memory format
   - particular memory format, i.e. `abcd` or `acdb`

    The benefit of using `any` memory format is that a more optimal implementation is chosen
The benefit of using a particular memory format is that no reorder is required, since user can use the output memory format of the parent primitive
For the most use cases we stick with the following approaches:
    - if the input memory is a part of the so called constant path (i.e. the input is the weights of the primitives), then `any` format can be used, since reorder will be done only once for all the inferences
    - if the input memory is a part of the NON constant path (i.e. the input is activation of the primitive), then the particular format should be used (format of the output memory of the parent primitive), since otherwise reorder will be executed for every inference of the model.

    This is, for example, why we use `any` format for the second input of inner_product primitive (second input is weights) but a particular format for the second input of the matmul primitive (both inputs are activations).
When we go back to the ACL interface, as far as I understand the idea is the same (opt_impl + reorder vs non_opt_impl_without_reorder). So it should be easy to follow the same principle here.
2. Sure, I am going to provide the examples soon

**Comment by renato-arantes** [comment] 2023-08-14 08:56
Hi @EgorDuplensky,

Can you give me some examples of how to reproduce the issues you are reporting?

Thanks,
Renato

**Comment by EgorDuplensky** [comment] 2023-09-08 12:03
> Hi @EgorDuplensky,
> 
> Can you give me some examples of how to reproduce the issues you are reporting?
> 
> Thanks, Renato

Hi,
Sorry for the late response.
1. An example of the reproduction for a matmul primitive
    oneDNN 3.1:
    `./build/tests/benchdnn/benchdnn --matmul --mode=p --reset --allow-enum-tags-only=0 --engine=cpu    --dt=f16:f16:f16  --stag=abcd --wtag=abcd --dtag=abcd --strides=::  --attr-scratchpad=user 1x12x128x64:1x12x64x128
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,gemm:acl,,--matmul --allow-enum-tags-only=false --mode=P --dt=f16:f16:f16 --stag=abcd --wtag=abcd --dtag=abcd --attr-scratchpad=user 1x12x128x64:1x12x64x128,0.0251658,0.0539579,466.397,0.0739864,340.141
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total perf: min(ms):0.0539579 avg(ms):0.0739864`
    oneDNN 3.2 (same primitive parameters):
    `./build/tests/benchdnn/benchdnn --matmul --mode=p --reset --allow-enum-tags-only=0 --engine=cpu    --dt=f16:f16:f16  --stag=abcd --wtag=abcd --dtag=abcd --strides=::  --attr-scratchpad=user 1x12x128x64:1x12x64x128
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,ref:any,,--mode=P --matmul --allow-enum-tags-only=false --dt=f16:f16:f16 --stag=abcd --wtag=abcd --dtag=abcd --attr-scratchpad=user 1x12x128x64:1x12x64x128,0.0251658,1549.65,0.0162396,1549.79,0.0162382
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total perf: min(ms):1549.65 avg(ms):1549.79`
    As you can see even if the user executes a primitive with the exactly same parameters it observes a huge performance degradation.
    As I already mentioned basically this is applicable for any matmul primitive, when wtag is set to a specific memory format
2. winograd convolution TBA

**Comment by vpirogov** [comment] 2023-12-17 05:39
Fixed by #1722

**Closed by vpirogov** 2023-12-17 05:39 UTC
Labels: bug
